import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;500;700&family=Railway:wght@200;500;700&display=swap"
        />
      </Head>
      <body className="font-Railway">
        <Providers>
        <Navbar/>
        </Providers>
        {children}
      </body>
    </html>
  );
}
