import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";
import {Poppins} from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700", "300"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
        <Navbar/>
        </Providers>
        {children}
      </body>
    </html>
  );
}
